In [1]:
import yaml
import torch
%load_ext autoreload
%autoreload 2
from aircraft_env import Location
from aircraft_env import AircraftEnv
from utils.units_converter import feet2meter

from itertools import product
from REINFORCE.reinforce_agent import REINFORCEAgent
import numpy as np
with open('REINFORCE/config.yaml') as f:
    templates = yaml.safe_load(f)
loc_1 = Location(45.46873715, -73.74257166095532)
loc_2 = Location(49.0068908, 2.5710819691019156)
loc_1, loc_2
env = AircraftEnv(arrival_location=loc_1, destination=loc_2, n_waypoints=9)
# agent = DQNAgent(templates, env=env, model_type=Net)
agent = REINFORCEAgent(templates, env)

Actions Number 25


In [3]:
agent.train()

Episode: 0:   0%|          | 7/30000 [00:00<04:15, 117.32it/s]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.], grad_fn=<SoftmaxBackward>) Categorical(probs: torch.Size([25]))
tensor(13)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.], grad_fn=<SoftmaxBackward>) Categorical(probs: torch.Size([25]))
tensor(20)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.], grad_fn=<SoftmaxBackward>) Categorical(probs: torch.Size([25]))
tensor(20)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.], grad_fn=<SoftmaxBackward>) Categorical(probs: torch.Size([25]))
tensor(14)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.], grad_fn=<SoftmaxBackward>) Categorical(probs: torch.Size([25]))
tensor(20)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 

RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated